### PR TITLE
Prep for web deploy

### PR DESCRIPTION
**Pull request by zimeon**
In preparation for web deploy setup I have populated the `site` directory with everything currently deployed on https://bibliotek-o.org/ including fixed for mixed-content necessary to repair https://bibliotek-o.org/ontology.html from the switch to HTTPS last week.

Relates to #35

### CODE REVIEW

**Comment by rjyounes** [comment]
I generally save the LODE doc as a single file with CSS and JS built in. Can that work here?

**Comment by zimeon** [comment]
That would avoid the mixed content issues but is not what was done last time

**Comment by rjyounes** [comment]
I have one file in both develop and master branches: ontology.html. Let's assume that that's what will be added to the repository going forward.

**Comment by zimeon** [comment]
Fine by me. The state of `site` in this PR is the current state of the website so we can make changes from there

**Comment by rjyounes** [comment]
OK. I don't know how it got that way because that's not the state on the master branch. 

Are you saying you want me to merge this PR and then you'll change the files?

**Comment by zimeon** [comment]
The only mismatches between the `ontology.html` on `master` and the one currently live (and in this PR) are the changes to avoid mixed-content issues that I fixed today. Neither include the CSS or JS inline:

```
sw272@lamp-legacy bibliotek-o>diff doc/LODE/ontology.html /cul/web/bibliotek-o.org/htdocs/ontology.html 
1c1
< <?xml version="1.0" encoding="UTF-8"?><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>bibliotek-o: a BIBFRAME 2 Ontology Extension</title><title>bibliotek-o: a BIBFRAME 2 Ontology Extension</title><link href="http://eelst.cs.unibo.it/apps/LODE/owl.css" rel="stylesheet" type="text/css" /><link href="http://eelst.cs.unibo.it/apps/LODE/Primer.css" rel="stylesheet" type="text/css" /><link href="http://eelst.cs.unibo.it/apps/LODE/rec.css" rel="stylesheet" type="text/css" /><link href="http://eelst.cs.unibo.it/apps/LODE/extra.css" rel="stylesheet" type="text/css" /><link rel="shortcut icon" href="http://eelst.cs.unibo.it/apps/LODE/favicon.ico" /><script src="http://eelst.cs.unibo.it/apps/LODE/jquery.js"></script><script src="http://eelst.cs.unibo.it/apps/LODE/jquery.scrollTo.js"></script><script src="http://eelst.cs.unibo.it/apps/LODE/marked.min.js"></script><script>
---
> <?xml version="1.0" encoding="UTF-8"?><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>bibliotek-o: a BIBFRAME 2 Ontology Extension</title><title>bibliotek-o: a BIBFRAME 2 Ontology Extension</title><link href="/LODE/owl.css" rel="stylesheet" type="text/css" /><link href="/LODE/Primer.css" rel="stylesheet" type="text/css" /><link href="/LODE/rec.css" rel="stylesheet" type="text/css" /><link href="/LODE/extra.css" rel="stylesheet" type="text/css" /><link rel="shortcut icon" href="/LODE/favicon.ico" /><script src="/LODE/jquery.js"></script><script src="/LODE/jquery.scrollTo.js"></script><script src="/LODE/marked.min.js"></script><script>
```

**Comment by zimeon** [comment]
After discussion with Alan I think I have to make a new PR against `master` in order for us to be able to test out these changes for auto-deploy ahead to making the (many) ontology updates in `develop`.

**Comment by rjyounes** [comment]
OK. Can you do it with the LODE in one file this time?

Most of the changes to the ontology are in the README, by the way. The only substantive changes have been the ones discussed by Steven and Amber. Jason added some doc files as well.

**Comment by zimeon** [comment]
I don't want to make any changes to the website with this deploy, if you want to update the LODE docs to use one with inline CSS and JS that should be a later PR. Will be good for testing the auto-deploy

**Pull request closed without merging**
