### PR TITLE
Add oa:Motivation individuals; modify ConservatorActivity definition

### PR DESCRIPTION
**Pull request by amberbilley**
Ignore f806d34 
Pull bd05afa

### CODE REVIEW

**Comment by dazza-codes** [comment]
@amberbilley 
- try using `git rebase -i HEAD~2` and follow the instructions to remove the commit you want to drop.  It might be possible to do so using the `gitk` utility if you prefer a visual tool.
  - https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
- all the whitespace changes in this are distracting and probably not necessary, we may need some kind of tool to remove or standardize whitespace formatting for the ontology file.  (Something like a vim-mode line is what I'm thinking about.)
  - maybe using `xmllint --format` is useful here and could be part of another PR that is merged before this one to standardize the whitespace and then we can proceed with this PR.
  - https://stackoverflow.com/questions/16090869/how-to-pretty-print-xml-from-the-command-line

**Comment by rjyounes** [comment]
It did not go through as a commit on the ld4l-labs:develop branch, only on your fork. So no need to worry about rebase.

**Review by rjyounes — CHANGES_REQUESTED** [review]
Can you make the local name and rdfs:label of specifyingSupplementaryContents consistent (either "content" or "contents")?

Restore specifyingSystemRequirements and add an owl:deprecated assertion: 
<owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean>true</owl:deprecated>

Add skos:changeNote assertions on changed items. See README.

**Comment by dazza-codes** [comment]
Minor process notes:
- it's common for a github PR to make a link in the initial description to the issues that are fixed by the PR
- it appears that this PR is "fixing" multiple issues and that's OK, although sometimes it's easier and turns out to be quicker to have a one-to-one relationship between issues and PRs.

**Comment by rjyounes** [comment]
@darrenleeweber We quite agree with your notes and you will find that is the process defined in the README. Members of the team are still getting used to the process and things will not be perfect from the start. Things rarely are.

The README in fact requests a 1-to-1 relationship between issues and PRs as it makes things much clearer and facilitates review of and decisions on the PRs.

**Comment by amberbilley** [comment]
Ok -- thanks for you feedback @darrenleeweber and @rjyounes. FYI -- I use the GitHub Desktop UI. I'm not that familiar with the command line of GitHub, so I can't run the commands that @darrenleeweber recommends. 

I'll make the changes you suggest.

**Comment by amberbilley** [comment]
Ok - made the changes as per your request.

**Comment by rjyounes** [comment]
I'm closing this PR due to the numerous confusing whitespace alterations. I've created PRs #52 and #53 instead. We'll figure out the whitespace issues later.

**Pull request closed without merging**
